fixed a typo

diff --git a/utgb-shell/src/main/java/org/utgenome/shell/script/bin/utgb b/utgb-shell/src/main/java/org/utgenome/shell/script/bin/utgb
--- a/utgb-shell/src/main/java/org/utgenome/shell/script/bin/utgb
+++ b/utgb-shell/src/main/java/org/utgenome/shell/script/bin/utgb
@@ -82,7 +82,7 @@ fi
 
 if [ ! -x "$JAVACMD" ] ; then
   echo "Error: JAVA_HOME is not defined correctly." 1>&2
-  echo "  We cannot execute $JAVACMD" > 1>&2
+  echo "  We cannot execute $JAVACMD" 1>&2
   exit 1
 fi
 
